services:
  plan-portal:
    build:
      context: .
      dockerfile: Dockerfile
      target: development

    ports:
      - "5173:5173"

    volumes:
      - /app/node_modules

    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src

        - action: rebuild
          path: package.json

        - action: rebuild
          path: package-lock.json
